<?php

namespace OC\TrickBundle\Repository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTricks()
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.name', 'ASC')
            ->leftJoin('t.pictures', 'pictures')
            ->addSelect('pictures')
            ->getQuery()
        ;

        return $qb->getResult();
    }

    public function findOneBySlug($slug)
    {
        $qb = $this
            ->createQueryBuilder('t')
            ->where('t.slug = :slug')
                ->setParameter('slug', $slug)
            ->leftJoin('t.pictures', 'pictures')
            ->addSelect('pictures')
            ->leftJoin('t.videos', 'videos')
            ->addSelect('videos')
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
