<?php

namespace OC\TrickBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends EntityRepository
{
    public function getTricks($page, $nbPerPage)
    {
        $qb = $this->createQueryBuilder('t')
            ->leftJoin('t.pictures', 'pictures')
            ->addSelect('pictures')
			->orderBy('t.name', 'ASC')
            ->getQuery()
        ;
		
		$qb->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage)
		;
		
		return new Paginator($qb, true);
    }

    public function findOneBySlug($slug)
    {
        $qb = $this
            ->createQueryBuilder('t')
            ->where('t.slug = :slug')
                ->setParameter('slug', $slug)
            ->leftJoin('t.pictures', 'pictures')
            ->addSelect('pictures')
            ->leftJoin('t.videos', 'videos')
            ->addSelect('videos')
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
