<?php

namespace OC\CommentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findByTrickWithLimit($trick, $offset)
    {
        $qb = $this
                ->createQueryBuilder('c')
                ->leftJoin('c.author', 'a')
                ->addSelect('a')
                ->where('c.trick = :trick')
                    ->setParameter('trick', $trick)
                ->orderBy('c.date', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults('10')
        ;
                    
        return $qb->getQuery()->getResult();
    }
}
